server:
  port: 8010
spring:
  application:
    name: sc-zuul-first-consumer
eureka:
  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    registerWithEureka: false 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
   
 
 

      
 
       
                                                                                     
                                                         