server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    registerWithEureka: false  
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。 
    fetchRegistry: false
    #Eureka Server的访问地址，服务注册和client获取服务注册信息均通过该URL，多个服务注册地址用,隔开
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: true
  user:
     name: xujin
     password: 123
  